---

- ansible.builtin.import_role:
    name: ome.omero_common

- name: omero-web | Include ome.selinux_utils
  ansible.builtin.include_role:
    name: ome.selinux_utils

- name: omero-web | Include python3_virtualenv role
  ansible.builtin.include_role:
    name: python3_virtualenv
  vars:
    python_version: "{{ python3_virtualenv_version }}"
    virtualenv_basedir: "{{ omero_web_basedir }}"
    service_name: "omero-web"

- name: omero-web | Include nginx role
  ansible.builtin.include_role:
    name: nginx
  when: omero_web_setup_nginx

- name: omero-web | Include ome.basedeps role
  ansible.builtin.include_role:
    name: ome.basedeps
