---

- src: ome.omero_common
- src: ome.nginx
# - src: ome.python3_virtualenv
- name: python3_virtualenv
  src: https://github.com/khaledk2/ansible-role-python3-virtualenv
  version: update_ansible_python
- src: ome.selinux_utils
- src: ome.redis
- src: ome.basedeps
